select * from customer limit 5;

-- q1. what is the total revenve generated by male and female customers?
Select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. which customers used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>(select avg(purchase_amount) from customer)

-- Q3. which are the top 5 products with the highest  average review rating?
select item_purchased, round(avg(review_rating),2) as rating 
from customer
group by item_purchased
order by rating DESC
limit 5;

-- Q4. Compare the average purchase amounts between Standard and express shipping?
select shipping_type, round(avg(purchase_amount),2) 
from customer
where shipping_type in ("Standard","Express")
group by shipping_type

-- Q5 Do subscripted customer spent more? compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status, 
count(customer_id) as total_customers,
round(AVG(purchase_amount),2) as average_total,
round(SUM(purchase_amount),2) as total_purchase
from customer
group by subscription_status
order by total_purchase,average_total DESC;

-- Q6. which 5 products have the highest percentage of purchase with discount applied?
select item_purchased,
round(100*sum(case when discount_applied="Yes" then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5;

-- Q7. Segment customers into new, returing and loyal based on their total number of previous purchases and 
-- show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases=1 THEN 	'NEW'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END as customer_segment
from customer
)
 select customer_segment, count(*) as "Number of customers"
 from customer_type
 group by customer_segment
 
 -- Q8. What are the top 3 most purchased products within each category?
 
 with item_counts as (
 select category,item_purchased,
 count(customer_id) as total_orders,
 ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank
 from customer
 group by category,item_purchased
 )
 select item_rank, category,item_purchased
 from item_counts
 where item_rank<=3
 
 -- Q9. Are customers who are repeat buyers( more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

-- Q10. What is the revenue by age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC;